version: '3'

services:

  # ----------------- #
  # Apache Spark      #
  # ----------------- #
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'
    volumes:
      - C:/Users/admin/LearningIT/20222/SmallData/Kafka_spark/traffic-flow-spark-kafka/data:/data
      - C:/Users/admin/LearningIT/20222/SmallData/Kafka_spark/traffic-flow-spark-kafka/src:/src
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2


    volumes:
      - C:/Users/admin/LearningIT/20222/SmallData/Kafka_spark/traffic-flow-spark-kafka/data:/data
      - C:/Users/admin/LearningIT/20222/SmallData/Kafka_spark/traffic-flow-spark-kafka/src:/src 

  # ----------------- #
  # Apache Kafka      #
  # ----------------- #
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      

    depends_on:
      - zookeeper
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - C:/Users/admin/LearningIT/20222/SmallData/Kafka_spark/traffic-flow-spark-kafka/elasticsearch_data1:/data
  kibana:
    image: docker.io/bitnami/kibana:8
    ports:
      - "5601:5601"
    volumes:
      - "C:/Users/admin/LearningIT/20222/SmallData/Kafka_spark/traffic-flow-spark-kafka/kibana_data:/bitnami/kibana"
    depends_on:
      - elasticsearch